# Generated by Django 5.0.6 on 2024-07-01 02:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NyaaaStore.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('descripcion', models.TextField(max_length=5000)),
                ('tp_producto', models.CharField(choices=[('FIGURA', 'FIGURA'), ('ACCESORIO', 'ACCESORIO'), ('POLERA', 'POLERA'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR')], default='SIN ESPECIFICAR', max_length=15)),
                ('precio', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400000)])),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('foto', models.ImageField(null=True, upload_to='productos')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NyaaaStore.anime')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NyaaaStore.marca')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NyaaaStore.serie')),
            ],
        ),
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono', models.CharField(max_length=9)),
                ('city', models.CharField(choices=[('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Concepción', 'Concepción'), ('Valparaíso', 'Valparaíso'), ('Tome', 'Tome')], max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
