# Generated by Django 5.0.6 on 2024-07-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0002_alter_producto_tp_producto_alter_userperfil_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('FIGURA', 'FIGURA'), ('ACCESORIO', 'ACCESORIO'), ('POLERA', 'POLERA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='city',
            field=models.CharField(choices=[('Concepción', 'Concepción'), ('Tome', 'Tome'), ('Santiago', 'Santiago'), ('Valparaíso', 'Valparaíso'), ('San Pedro', 'San Pedro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO'), ('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
