# Generated by Django 5.0.6 on 2024-07-02 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0003_alter_producto_tp_producto_alter_userperfil_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('ACCESORIO', 'ACCESORIO'), ('POLERA', 'POLERA'), ('FIGURA', 'FIGURA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono', models.CharField(max_length=9)),
                ('city', models.CharField(choices=[('Valparaíso', 'Valparaíso'), ('Santiago', 'Santiago'), ('Tome', 'Tome'), ('San Pedro', 'San Pedro'), ('Concepción', 'Concepción')], max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPerfil',
        ),
    ]
