# Generated by Django 5.0.6 on 2024-07-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0004_alter_producto_tp_producto_alter_venta_estado_perfil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='city',
            field=models.CharField(blank=True, choices=[('Tome', 'Tome'), ('Concepción', 'Concepción'), ('San Pedro', 'San Pedro'), ('Santiago', 'Santiago'), ('Valparaíso', 'Valparaíso')], max_length=15),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fono',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('POLERA', 'POLERA'), ('ACCESORIO', 'ACCESORIO'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('FIGURA', 'FIGURA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PREPARADO', 'PREPARADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENTREGADO', 'ENTREGADO'), ('ENVIADO', 'ENVIADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
