# Generated by Django 5.0.6 on 2024-07-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0006_alter_perfil_city_alter_producto_tp_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='city',
            field=models.CharField(blank=True, choices=[('Tome', 'Tome'), ('San Pedro', 'San Pedro'), ('Santiago', 'Santiago'), ('Concepción', 'Concepción'), ('Valparaíso', 'Valparaíso')], max_length=15),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('POLERA', 'POLERA'), ('ACCESORIO', 'ACCESORIO'), ('FIGURA', 'FIGURA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('PREPARADO', 'PREPARADO'), ('ENVIADO', 'ENVIADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
