# Generated by Django 5.0.6 on 2024-07-02 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0007_alter_perfil_city_alter_producto_tp_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('ACCESORIO', 'ACCESORIO'), ('FIGURA', 'FIGURA'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('POLERA', 'POLERA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENVIADO', 'ENVIADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENTREGADO', 'ENTREGADO'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
        migrations.CreateModel(
            name='UserPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fono', models.CharField(max_length=9)),
                ('city', models.CharField(choices=[('San Pedro', 'San Pedro'), ('Tome', 'Tome'), ('Valparaíso', 'Valparaíso'), ('Concepción', 'Concepción'), ('Santiago', 'Santiago')], max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
