# Generated by Django 5.0.6 on 2024-07-05 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NyaaaStore', '0008_alter_producto_tp_producto_alter_venta_estado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tp_producto',
            field=models.CharField(choices=[('ACCESORIO', 'ACCESORIO'), ('SIN ESPECIFICAR', 'SIN ESPECIFICAR'), ('POLERA', 'POLERA'), ('FIGURA', 'FIGURA')], default='SIN ESPECIFICAR', max_length=15),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='city',
            field=models.CharField(choices=[('Santiago', 'Santiago'), ('San Pedro', 'San Pedro'), ('Tome', 'Tome'), ('Concepción', 'Concepción'), ('Valparaíso', 'Valparaíso')], max_length=15),
        ),
        migrations.AlterField(
            model_name='userperfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userperfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('ENTREGADO', 'ENTREGADO'), ('EN PREPARACIÓN', 'EN PREPARACIÓN'), ('ENVIADO', 'ENVIADO'), ('PREPARADO', 'PREPARADO')], default='EN PREPARACIÓN', max_length=30),
        ),
    ]
